"""Reusable UPGMA tree reconstruction from a labelled distance matrix."""

from __future__ import annotations

from dataclasses import dataclass
import json
import math
from pathlib import Path
from typing import Any


@dataclass
class Cluster:
    """Represent one leaf or internal cluster in a reconstructed tree.

    :param name: Deterministic name used to identify and order the cluster.
    :param members: Taxon labels contained in the cluster.
    :param height: Distance from every descendant tip to this cluster.
    :param left: First child cluster, or None for a leaf.
    :param right: Second child cluster, or None for a leaf.
    :param left_branch_length: Branch length from this cluster to its left child.
    :param right_branch_length: Branch length from this cluster to its right child.
    """

    name: str
    members: tuple[str, ...]
    height: float
    left: Cluster | None = None
    right: Cluster | None = None
    left_branch_length: float | None = None
    right_branch_length: float | None = None


def validate_distance_matrix(labels: list[str], matrix: list[list[float]]) -> None:
    """Validate labels and values for UPGMA reconstruction.

    :param labels: Ordered taxon labels corresponding to matrix rows and columns.
    :param matrix: Square symmetric matrix of finite, non-negative distances.
    :return: None.
    """
    if len(labels) < 2:
        raise ValueError("Distance matrix must contain at least two taxa")
    if any(not isinstance(label, str) or not label.strip() for label in labels):
        raise ValueError("All taxa must have non-empty string labels")
    if len(set(labels)) != len(labels):
        raise ValueError("Taxon labels must be unique")
    if len(matrix) != len(labels):
        raise ValueError("Distance matrix must be square and match the number of labels")

    for row_index, row in enumerate(matrix):
        if not isinstance(row, list) or len(row) != len(labels):
            raise ValueError("Distance matrix must be square and contain every taxon pair")

        for column_index, value in enumerate(row):
            # Booleans are numbers in Python, but are not meaningful evolutionary distances.
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ValueError(
                    f"Distance at row {row_index}, column {column_index} must be numeric"
                )
            if not math.isfinite(value):
                raise ValueError(
                    f"Distance at row {row_index}, column {column_index} must be finite"
                )
            if value < 0:
                raise ValueError("Distances must be non-negative")

        # A taxon's distance from itself must be exactly zero.
        if row[row_index] != 0:
            raise ValueError("Diagonal distances must be zero")

    for row_index in range(len(labels)):
        for column_index in range(row_index + 1, len(labels)):
            # Tight absolute tolerance allows harmless floating-point serialisation noise.
            if not math.isclose(
                matrix[row_index][column_index],
                matrix[column_index][row_index],
                rel_tol=0.0,
                abs_tol=1e-12,
            ):
                raise ValueError("Distance matrix must be symmetric")


def load_distance_matrix(path: str | Path) -> tuple[list[str], list[list[float]]]:
    """Load and validate a distance matrix JSON file.

    :param path: JSON file generated by the distance matrix calculator.
    :return: Ordered taxon labels and their square distance matrix.
    """
    payload = _load_distance_matrix_payload(path)
    labels = payload["labels"]
    matrix = payload["matrix"]
    validate_distance_matrix(labels, matrix)
    return labels, matrix


def load_distance_matrix_with_metric(
    path: str | Path,
) -> tuple[list[str], list[list[float]], str]:
    """Load a validated distance matrix and its distance metric.

    :param path: JSON file generated by the distance matrix calculator.
    :return: Ordered taxon labels, square distance matrix, and distance metric.
    """
    payload = _load_distance_matrix_payload(path)
    labels = payload["labels"]
    matrix = payload["matrix"]
    distance_metric = payload.get("distance_metric")

    # Restrict the metric to filename-safe identifiers before using it in default output paths.
    if (
        not isinstance(distance_metric, str)
        or not distance_metric
        or not all(character.isalnum() or character in "_-" for character in distance_metric)
    ):
        raise ValueError(
            "Distance matrix JSON must contain a filename-safe 'distance_metric' string"
        )

    validate_distance_matrix(labels, matrix)
    return labels, matrix, distance_metric


def _load_distance_matrix_payload(path: str | Path) -> dict[str, Any]:
    """Decode the object stored in a distance matrix JSON file.

    :param path: JSON file generated by the distance matrix calculator.
    :return: Decoded top-level distance matrix object.
    """
    input_path = Path(path)
    if not input_path.exists():
        raise ValueError(f"Input distance matrix does not exist: {input_path}")
    if not input_path.is_file():
        raise ValueError(f"Input distance matrix path is not a file: {input_path}")

    try:
        # The calculator stores labels and matrix values as top-level JSON fields.
        with input_path.open(encoding="utf-8") as handle:
            payload: Any = json.load(handle)
    except json.JSONDecodeError as error:
        raise ValueError(f"Input distance matrix is not valid JSON: {error.msg}") from error

    if not isinstance(payload, dict):
        raise ValueError("Distance matrix JSON must contain an object")
    labels = payload.get("labels")
    matrix = payload.get("matrix")
    if not isinstance(labels, list) or not isinstance(matrix, list):
        raise ValueError("Distance matrix JSON must contain 'labels' and 'matrix' lists")
    return payload


def cluster_distance(
    first: Cluster,
    second: Cluster,
    labels: list[str],
    matrix: list[list[float]],
) -> float:
    """Calculate the arithmetic mean distance between two clusters.

    :param first: First cluster in the comparison.
    :param second: Second cluster in the comparison.
    :param labels: Ordered taxon labels corresponding to the distance matrix.
    :param matrix: Original validated pairwise distance matrix.
    :return: Mean of all member-to-member distances between the clusters.
    """
    # Resolve labels once, then average every cross-cluster member pair without weighting clusters.
    label_indexes = {label: index for index, label in enumerate(labels)}
    try:
        distances = [
            matrix[label_indexes[first_member]][label_indexes[second_member]]
            for first_member in first.members
            for second_member in second.members
        ]
    except KeyError as error:
        raise ValueError(f"Cluster contains unknown taxon: {error.args[0]}") from error

    if not distances:
        raise ValueError("Clusters must each contain at least one taxon")
    return sum(distances) / len(distances)


def upgma(labels: list[str], matrix: list[list[float]]) -> Cluster:
    """Reconstruct a rooted ultrametric tree with UPGMA.

    :param labels: Ordered taxon labels corresponding to matrix rows and columns.
    :param matrix: Square symmetric matrix of pairwise taxon distances.
    :return: Root cluster of the reconstructed tree.
    """
    validate_distance_matrix(labels, matrix)

    # Start with one height-zero leaf cluster for each taxon.
    clusters = [
        Cluster(name=label, members=(label,), height=0.0)
        for label in sorted(labels)
    ]

    while len(clusters) > 1:
        # Sorting pair keys makes equal-distance merges deterministic across input orderings.
        candidates = [
            (
                cluster_distance(left, right, labels, matrix),
                tuple(sorted((left.name, right.name))),
                left,
                right,
            )
            for left_index, left in enumerate(clusters)
            for right in clusters[left_index + 1:]
        ]
        distance, _, first, second = min(
            candidates,
            key=lambda candidate: (candidate[0], candidate[1]),
        )
        left, right = sorted((first, second), key=lambda cluster: cluster.name)
        new_height = distance / 2.0

        # Child lengths are measured from the new merge height to each child's height.
        merged_members = tuple(sorted(left.members + right.members))
        merged = Cluster(
            name="+".join(merged_members),
            members=merged_members,
            height=new_height,
            left=left,
            right=right,
            left_branch_length=new_height - left.height,
            right_branch_length=new_height - right.height,
        )

        # Replace both children with their parent, retaining name order for stable ties.
        clusters = [
            cluster for cluster in clusters
            if cluster is not first and cluster is not second
        ]
        clusters.append(merged)
        clusters.sort(key=lambda cluster: cluster.name)

    return clusters[0]


def to_newick(cluster: Cluster) -> str:
    """Serialise a reconstructed cluster tree as Newick with branch lengths.

    :param cluster: Root cluster returned by upgma.
    :return: Newick tree ending with a semicolon.
    """
    def render(node: Cluster) -> str:
        """Render one node and its descendants without a trailing semicolon.

        :param node: Current leaf or internal cluster.
        :return: Newick fragment for the node.
        """
        # Leaves contribute their label; internal nodes recursively contribute two children.
        if node.left is None and node.right is None:
            return _quote_newick_label(node.name)
        if (
            node.left is None
            or node.right is None
            or node.left_branch_length is None
            or node.right_branch_length is None
        ):
            raise ValueError("Internal clusters must have two children and two branch lengths")

        return (
            f"({render(node.left)}:{node.left_branch_length:.6f},"
            f"{render(node.right)}:{node.right_branch_length:.6f})"
        )

    # Newick represents the root by the outermost group and a terminating semicolon.
    return f"{render(cluster)};"


def write_newick(cluster: Cluster, path: str | Path) -> Path:
    """Write a reconstructed tree to a Newick file.

    :param cluster: Root cluster returned by upgma.
    :param path: Destination file path.
    :return: Destination path after writing.
    """
    output_path = Path(path)
    # Create parent directories so the CLI can target a new output folder directly.
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(f"{to_newick(cluster)}\n", encoding="utf-8")
    return output_path


def _quote_newick_label(label: str) -> str:
    """Quote a taxon label when it contains Newick punctuation or whitespace.

    :param label: Taxon label to encode.
    :return: Newick-safe taxon label.
    """
    # Single-quoted labels escape embedded apostrophes by doubling them.
    if any(character.isspace() or character in "(),:;[]'" for character in label):
        escaped_label = label.replace("'", "''")
        return f"'{escaped_label}'"
    return label
