"""Shared Graphviz text and image helpers."""

from __future__ import annotations

import shutil
import subprocess


def dot_escape(value: str) -> str:
    """Escape text embedded in a quoted Graphviz string.

    :param value: Raw label, identifier, or title.
    :return: Graphviz-safe quoted-string content.
    """
    # Escape backslashes first so later replacements are not double-interpreted.
    return value.replace("\\", "\\\\").replace("\n", "\\n").replace('"', '\\"')


def render_dot_png(dot_source: str) -> bytes:
    """Render Graphviz DOT source to PNG bytes.

    :param dot_source: DOT source describing the graphic to render.
    :return: PNG image bytes generated by Graphviz.
    """
    # Downloads require the concrete Graphviz executable rather than Streamlit rendering.
    if shutil.which("dot") is None:
        raise RuntimeError("Graphviz 'dot' command is required for PNG export")

    completed = subprocess.run(
        ["dot", "-Tpng"],
        input=dot_source.encode("utf-8"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    return completed.stdout
